export const section = "bg-gradient-to-br from-brand-strong via-brand-deep to-brand-deeper px-6 py-16 text-content-inverse md:py-20";
export const container = "mx-auto max-w-6xl text-center";
export const heading = "mb-6 text-3xl font-bold md:text-4xl font-[family-name:var(--font-space-grotesk)]";
export const description = "mx-auto mb-8 max-w-2xl text-lg text-content-inverse";
export const row = "flex flex-wrap justify-center gap-4";
export const primaryLink = "group inline-flex min-h-11 items-center gap-2 rounded-lg bg-surface px-6 py-2.5 font-medium text-brand-strong transition-[background-color,transform,box-shadow] duration-300 hover:-translate-y-0.5 hover:bg-surface-muted hover:shadow-lg";
export const secondaryLink = "group inline-flex min-h-11 items-center gap-2 rounded-lg border border-brand-tint bg-brand-deep px-6 py-2.5 font-medium text-content-inverse transition-[background-color,border-color,transform] duration-300 hover:-translate-y-0.5 hover:border-surface hover:bg-brand-deeper";
export const tertiaryLink = "group inline-flex min-h-11 items-center gap-2 rounded-lg border border-brand-tint/85 bg-transparent px-6 py-2.5 font-medium text-content-inverse transition-[background-color,border-color,transform] duration-300 hover:-translate-y-0.5 hover:border-surface hover:bg-brand-deeper/45";
export const icon = "h-4 w-4 transition-transform duration-200 ease-out group-hover:translate-x-0.5 group-focus-visible:translate-x-0.5";
