export const section = "bg-surface px-6 py-12 md:py-20";
export const container = "mx-auto max-w-6xl";
export const panel = "rounded-2xl border border-border-subtle bg-surface-muted/55 p-5 sm:p-6 md:p-8";
export const eyebrow = "mb-4 text-sm font-semibold uppercase tracking-wider text-brand";
export const block = "max-w-4xl";
export const paragraphReveal = "relative pl-4 sm:pl-5 before:absolute before:left-0 before:top-2 before:h-2 before:w-2 before:rounded-full before:bg-brand-tint";
export const paragraph = "leading-relaxed text-content-muted";
export const paragraphLead = "text-content";
export const paragraphSpacing = "mb-5 sm:mb-6";
