import { spacing, typeScale } from "@/features/shared/designSystem";

export const section = `${spacing.section} bg-surface`;
export const container = spacing.container5;
export const intro = `${spacing.introBlock} text-center`;
export const eyebrow = typeScale.eyebrow;
export const heading = typeScale.sectionTitle;
export const description = `mx-auto max-w-2xl ${typeScale.sectionDescription}`;
export const grid = "grid gap-4 sm:gap-5 md:grid-cols-2 xl:grid-cols-3";
export const cardReveal = "h-full";
export const card = "group flex h-full flex-col rounded-xl border border-border-default bg-surface p-4 shadow-sm transition-[border-color,box-shadow] duration-300 hover:border-border-default/80 hover:shadow-md sm:p-5";
export const anchorOffset = "scroll-mt-28 md:scroll-mt-32";
export const imageFrame = "mb-3 overflow-hidden rounded-lg bg-surface-muted";
export const image = "aspect-[16/10] h-auto w-full object-cover transition-transform duration-500 motion-safe:group-hover:scale-[1.02] sm:aspect-[10/7]";
export const cardRow = "mb-2 flex items-center justify-between gap-2";
export const badge = `inline-flex rounded-full bg-brand-soft px-2 py-0.5 ${typeScale.metaLabel} text-brand sm:px-2.5 sm:py-1`;
export const timeline = `${typeScale.metaLabel} text-content-subtle`;
export const subheading = `${typeScale.cardTitle} mb-2`;
export const cardDescription = "mb-3 text-sm leading-relaxed text-content-muted";
export const featureList = "mb-3 list-disc space-y-1 pl-5 text-sm leading-relaxed text-content-muted";
export const price = "mt-auto pt-2 text-base font-semibold text-brand";
