import { spacing, typeScale } from "@/features/shared/designSystem";

export const section = `${spacing.section} relative overflow-hidden bg-surface`;
export const ambientBackdrop = "pointer-events-none absolute inset-0 bg-[radial-gradient(120%_120%_at_8%_0%,var(--color-brand-weak)_0%,transparent_60%),radial-gradient(120%_120%_at_92%_100%,var(--color-brand-soft)_0%,transparent_62%)] opacity-65";
export const container = `relative ${spacing.container6}`;
export const intro = `${spacing.introBlock} sm:mb-9`;
export const heading = `${typeScale.sectionTitle} mb-2`;
export const introDescription = `max-w-[62ch] text-balance ${typeScale.sectionDescription}`;
export const grid = "grid gap-4 sm:gap-6 md:grid-cols-3";
export const card = "rounded-xl border border-border-default bg-surface p-4 shadow-[0_14px_24px_-22px_var(--color-neutral-900)] transition-[transform,border-color,box-shadow] duration-300 hover:-translate-y-0.5 hover:border-brand-tint hover:shadow-xl sm:rounded-2xl sm:border-border-subtle sm:p-6 sm:shadow-sm";
export const primaryCard = "rounded-xl border border-brand-tint bg-gradient-to-br from-brand-weak via-surface to-brand-soft p-4 shadow-[0_18px_40px_-30px_var(--color-brand)] ring-1 ring-brand-tint/60 transition-[transform,box-shadow] duration-300 hover:-translate-y-0.5 hover:shadow-[0_24px_56px_-32px_var(--color-brand)] sm:rounded-2xl sm:p-6";
export const row = "mb-3 flex h-10 w-10 items-center justify-center rounded-lg bg-brand-soft sm:mb-4 sm:h-12 sm:w-12 sm:rounded-xl";
export const primaryRow = "mb-3 flex h-10 w-10 items-center justify-center rounded-lg bg-brand sm:mb-4 sm:h-12 sm:w-12 sm:rounded-xl";
export const icon = "h-5 w-5 text-brand sm:h-6 sm:w-6";
export const iconInverse = "h-5 w-5 text-content-inverse sm:h-6 sm:w-6";
export const priorityBadge = `mb-3 inline-flex rounded-full border border-brand-tint bg-brand-soft px-2.5 py-1 ${typeScale.metaLabel} text-brand-strong`;
export const subheading = `${typeScale.cardTitle} mb-2`;
export const description = "mb-4 text-sm leading-relaxed text-content-muted sm:mb-5 sm:text-base";
export const link = "group inline-flex min-h-[44px] items-center gap-2 text-sm font-medium text-brand transition-colors hover:text-brand-strong hover:underline hover:underline-offset-4 sm:text-base";
export const primaryLink = "group inline-flex min-h-[44px] w-full items-center justify-center gap-2 rounded-lg bg-brand px-4 py-2 text-sm font-semibold text-content-inverse shadow-[0_10px_20px_-16px_var(--color-brand)] transition-[background-color,transform] duration-200 hover:-translate-y-0.5 hover:bg-brand-strong sm:w-auto";
export const linkIcon = "h-4 w-4 transition-transform duration-200 ease-out group-hover:translate-x-0.5 group-focus-visible:translate-x-0.5";
