import { spacing, typeScale } from "@/features/shared/designSystem";

export const section = `${spacing.section} relative overflow-hidden bg-surface`;
export const ambientBackdrop = "pointer-events-none absolute inset-0 bg-[radial-gradient(120%_120%_at_8%_0%,var(--color-brand-weak)_0%,transparent_58%),radial-gradient(120%_120%_at_92%_100%,var(--color-brand-soft)_0%,transparent_62%)] opacity-70";
export const container = `relative ${spacing.container6}`;
export const block = "mb-12 text-center";
export const eyebrow = typeScale.eyebrow;
export const subheading = typeScale.sectionTitle;
export const description = `mx-auto ${typeScale.sectionDescription}`;
export const grid = "grid gap-6 md:grid-cols-2 xl:grid-cols-3";
export const cardWrap = "h-full";
export const card = "group relative isolate block h-full overflow-hidden rounded-2xl border border-border-subtle bg-surface/95 p-5 shadow-sm transition-[transform,border-color,box-shadow] duration-300 hover:-translate-y-0.5 hover:border-brand-tint hover:shadow-xl focus-visible:-translate-y-0.5 focus-visible:border-brand-tint focus-visible:shadow-xl focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-brand md:p-6";
export const glow = "pointer-events-none absolute -right-10 -top-10 h-24 w-24 rounded-full bg-brand-weak opacity-45 blur-2xl transition-opacity duration-300 group-hover:opacity-90";
export const illustrationWrap = "mb-4 flex items-center justify-center md:mb-5";
export const serviceImage = "h-36 w-36 object-contain transition-transform duration-300 group-hover:scale-[1.03] sm:h-40 sm:w-40 md:h-52 md:w-52";
export const cardTitle = `${typeScale.cardTitle} mb-1 md:mb-2`;
export const text = "mb-3 text-sm leading-relaxed text-content-muted md:mb-4";
export const outcome = "mb-2 text-sm leading-relaxed text-content-muted md:mb-3";
export const hint = `${typeScale.metaLabel} mb-3 text-brand-strong md:mb-4`;
export const tagList = "flex flex-wrap gap-2";
export const tag = `rounded-full border border-brand-tint bg-brand-weak px-2.5 py-1 ${typeScale.metaLabel} text-brand-strong`;
export const bottomCtaRow = "mt-8 text-center";
export const bottomCta = "group inline-flex items-center gap-2 rounded-full border border-brand-tint bg-brand-weak px-4 py-2 text-sm font-semibold text-brand transition-[color,border-color,transform] duration-200 hover:-translate-y-0.5 hover:border-brand hover:text-brand-strong focus-visible:-translate-y-0.5 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-brand";
export const bottomCtaIcon = "h-4 w-4 transition-transform duration-200 ease-out group-hover:translate-x-0.5 group-focus-visible:translate-x-0.5";
